schema_version: 1

context:
  name: pylsp-rope
  version: 0.1.17

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylsp_rope-${{ version }}.tar.gz
  sha256: 4cd6f2fb32c84302b94cb4ce002bc0700b1b656dd5147e7db3dd92303a9a8dc2

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - python-lsp-server-base
    - rope >=0.21.0
    - typing_extensions

tests:
  - python:
      imports:
        - pylsp_rope
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Extended refactoring capabilities for Python LSP Server using Rope.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/python-rope/pylsp-rope

extra:
  recipe-maintainers:
    - JaRoSchm
